title: Evan DeBlase # your name (or website title) here
logo: "/images/Me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="www.linkedin.com/in/evan-deblase">LinkedIn</a> 
  <br>
  <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/evandeblase">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
