title: Evan DeBlase # your name (or website title) here
logo: <img class="img-circle" src="/images/Me.png?raw=True" width="50%"> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  <a href="www.linkedin.com/in/evan-deblase">LinkedIn</a> 
  <br>
  <a href="https://github.com/evandeblase">GitHub</a>  
  <br>
  <a href="images/Evan DeBlase Resume.pdf" class="btn btn--info">Resume</a>
  
theme: jekyll-theme-minimal
